### ISSUE TITLE
Application to reproduce the experimental results of the industrial dataset

### ISSUE THREAD

**Issue by surqing** [YuanchenBei/MacGNN#2]
Hello, I am very interested in your work, can you provide the download link of industrial dataset？If possible, please send it to my email wu.surqing@gmail.com or reply to me directly.

**Comment by YuanchenBei** [comment]
Thank you for your interest in our paper! As the industrial dataset is real large-scale data from Alibaba's production environment, based on the company's data privacy policy, we are unable to make the industrial data public. The other public datasets involved in the paper are all accessible in Google Drive. I hope these can help your reproduction.

**Comment by surqing** [comment]
Okay, thank you for your reply.
