### ISSUE TITLE
The data processing code produces files that are inconsistent with the downloaded processed dataset

### ISSUE THREAD

**Issue by surqing** [YuanchenBei/MacGNN#3]
I used `ml-process.py` in your `./data/mag` directory to generate the processed dataset. The script generated two files, `remap.pkl` and `uc_cluster_kmeans.pkl`,
![image](https://github.com/YuanchenBei/MacGNN/assets/84219482/8cc5736d-8139-46ac-8f8d-2087d6c96d76)
 but, The content and size of both files are inconsistent with the `ml-10m.pkl` downloaded from your Google Drive. By reading found that their stored data type is not consistent, is a `pandas.core.DataFrame` and another is `numpy.ndarray`.
**Is there any code or file missing for further processing?**

**Comment by YuanchenBei** [comment]
> I used `ml-process.py` in your `./data/mag` directory to generate the processed dataset. The script generated two files, `remap.pkl` and `uc_cluster_kmeans.pkl`, ![image](https://private-user-images.githubusercontent.com/84219482/344366248-8cc5736d-8139-46ac-8f8d-2087d6c96d76.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2NDUyNzYsIm5iZiI6MTcxOTY0NDk3NiwicGF0aCI6Ii84NDIxOTQ4Mi8zNDQzNjYyNDgtOGNjNTczNmQtODEzOS00NmFjLThmOGQtMjA4N2Q2Yzk2ZDc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI5VDA3MDkzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzMGIwYTY2NzdjNzQ0MzRjN2YxOGRjY2M5MGZkYTY0NDcwNmQ3ZTBhZjE3OTUzZGE3ZTk0YTdhNmM0NTIwZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bl9akcwJlU2fzLrMCZJyjzVMwsVrbnPRPUxfqfQClO4) but, The content and size of both files are inconsistent with the `ml-10m.pkl` downloaded from your Google Drive. By reading found that their stored data type is not consistent, is a `pandas.core.DataFrame` and another is `numpy.ndarray`. **Is there any code or file missing for further processing?**

Hi, thanks for the question. In fact, the data in Google Drive has been pre-processed, which you can directly use for the model running without any further preprocessing. The provided ml-process.py file is an example of data processing if you have raw/new dataset data.

**Comment by surqing** [comment]
I'm sorry I didn't describe my problem clearly. I just want to use the ml_process.py file to process the raw ml-10m dataset that download from https://grouplens.org/datasets/movielens/10m/. But the generating .pkl file is not the same as the one downloaded from Google Drive and I don't know why. The two files generated by running.ml_process.py are named remap.pkl and uc_cluster_kmeans.pkl, which were framed in red in my last conversation.

**Comment by YuanchenBei** [comment]
> I'm sorry I didn't describe my problem clearly. I just want to use the ml_process.py file to process the raw ml-10m dataset that download from https://grouplens.org/datasets/movielens/10m/. But the generating .pkl file is not the same as the one downloaded from Google Drive and I don't know why. The two files generated by running.ml_process.py are named remap.pkl and uc_cluster_kmeans.pkl, which were framed in red in my last conversation.

Hi! The final generated ml-10m.pkl file is placed in the parent directory (see the figure below), while the two files you marked in red are generated in the current directory. I think the ml-10m.pkl file you downloaded has been directly overwritten by the generated file.

Hope this will help you.

<img width="969" alt="image" src="https://github.com/YuanchenBei/MacGNN/assets/47875143/ea2b14d7-c155-4480-b2fc-bc187d18b8e1">

**Comment by surqing** [comment]
Oh right! Thank you very much for your patience, I thought it would be generated in the `mag` directory
